from __future__ import annotations

import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0002_remaining_tables"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column("resources", "location", type_=Geography(geometry_type="POINT", srid=4326), postgresql_using="ST_GeogFromText(location)")
    op.create_table("agent_mandates", sa.Column("mandate_id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("agent_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("agents.agent_id"), nullable=False), sa.Column("owner_entity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("owner_entities.owner_entity_id"), nullable=False), sa.Column("scope", postgresql.JSONB, nullable=False), sa.Column("allowed_object_types", postgresql.JSONB, nullable=False), sa.Column("allowed_actions", postgresql.JSONB, nullable=False), sa.Column("allowed_regions", postgresql.JSONB, nullable=False), sa.Column("property_markings", postgresql.JSONB, nullable=False), sa.Column("propagation_markings", postgresql.JSONB, nullable=False), sa.Column("limits", postgresql.JSONB, nullable=False), sa.Column("approval_mode", sa.String(32), nullable=False), sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False), sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False), sa.Column("version", sa.Integer, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("negotiation_participants", sa.Column("negotiation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("negotiations.negotiation_id"), primary_key=True), sa.Column("agent_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("agents.agent_id"), primary_key=True), sa.Column("role", sa.String(32), nullable=False), sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False), sa.Column("left_at", sa.DateTime(timezone=True)), sa.Column("final_status", sa.String(32)))
    op.create_table("messages", sa.Column("message_id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("negotiation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("negotiations.negotiation_id"), nullable=False), sa.Column("from_agent_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("agents.agent_id"), nullable=False), sa.Column("to_agent_id", postgresql.UUID(as_uuid=True)), sa.Column("message_type", sa.String(32), nullable=False), sa.Column("payload", postgresql.JSONB, nullable=False), sa.Column("signature", sa.LargeBinary, nullable=False), sa.Column("nonce", postgresql.UUID(as_uuid=True), nullable=False, unique=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("sequence_number", sa.Integer, nullable=False), sa.Column("parent_message_id", postgresql.UUID(as_uuid=True)))
    op.create_table("agreements", sa.Column("agreement_id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("negotiation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("negotiations.negotiation_id"), nullable=False), sa.Column("terms", postgresql.JSONB, nullable=False), sa.Column("parties", postgresql.JSONB, nullable=False), sa.Column("signatures", postgresql.JSONB, nullable=False), sa.Column("state", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("settled_at", sa.DateTime(timezone=True)), sa.Column("audit_hash", sa.LargeBinary, nullable=False))
    op.create_table("approval_requests", sa.Column("approval_id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("negotiation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("negotiations.negotiation_id"), nullable=False), sa.Column("agreement_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("agreements.agreement_id")), sa.Column("owner_entity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("owner_entities.owner_entity_id"), nullable=False), sa.Column("required_role", sa.String(32), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("displayed_terms_hash", sa.LargeBinary, nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("approval_decisions", sa.Column("approval_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("approval_requests.approval_id"), primary_key=True), sa.Column("approver_user_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("decision", sa.String(32), nullable=False), sa.Column("reason", sa.String(1024)), sa.Column("displayed_terms_hash", sa.LargeBinary, nullable=False), sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("trust_score_history", sa.Column("agent_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("agents.agent_id"), primary_key=True), sa.Column("calculated_at", sa.DateTime(timezone=True), primary_key=True), sa.Column("score", sa.Numeric(5, 4), nullable=False), sa.Column("calculation_method", sa.String(64), nullable=False), sa.Column("input_signals", postgresql.JSONB, nullable=False))
    op.create_table("price_signal_history", sa.Column("price_signal_id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("domain_id", sa.String(64), nullable=False), sa.Column("resource_type", sa.String(128), nullable=False), sa.Column("region", sa.String(64), nullable=False), sa.Column("unit_price_yen", sa.Numeric, nullable=False), sa.Column("quantity_kg", sa.Numeric, nullable=False), sa.Column("agreement_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("agreements.agreement_id"), nullable=False), sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("mandate_adjustment_recommendations", sa.Column("recommendation_id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("agent_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("agents.agent_id"), nullable=False), sa.Column("owner_entity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("owner_entities.owner_entity_id"), nullable=False), sa.Column("approval_rate", sa.Numeric(5, 4), nullable=False), sa.Column("reject_reasons", postgresql.JSONB, nullable=False), sa.Column("recommended_change", postgresql.JSONB, nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("matching_outcome_metrics", sa.Column("metric_id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("domain_id", sa.String(64), nullable=False), sa.Column("matching_policy", sa.String(64), nullable=False), sa.Column("candidate_count", sa.Integer, nullable=False), sa.Column("negotiation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("negotiations.negotiation_id"), nullable=False), sa.Column("outcome", sa.String(32), nullable=False), sa.Column("elapsed_seconds", sa.Numeric, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))


def downgrade() -> None:
    for table in ("matching_outcome_metrics", "mandate_adjustment_recommendations", "price_signal_history", "trust_score_history", "approval_decisions", "approval_requests", "agreements", "messages", "negotiation_participants", "agent_mandates"):
        op.drop_table(table)
    op.alter_column("resources", "location", type_=sa.Text(), postgresql_using="ST_AsText(location::geometry)")
